dataset_name: default
dataset_path: ChanceFocus/en-fpb
output_type: multiple_choice
doc_to_target: gold
doc_to_text: "{{text}}"
doc_to_choice: "{{choices}}"
fewshot_split: train
should_decontaminate: true
doc_to_decontamination_query: "{{text}}"
generation_kwargs:
  do_sample: false
  temperature: 0.0
  max_gen_toks: 128
metric_list:
  - metric: !function reg_utils.acc
    aggregation: !function reg_utils.acc_agg
    higher_is_better: true
  - metric: !function reg_utils.f1
    aggregation: !function reg_utils.f1_agg
    higher_is_better: true
metadata:
  version: '1.0'
  task_type: "sentiment-classification"
task: Leaderboard_FPB
tag: OpenFinLLM-Leaderboard
test_split: test
training_split: train